apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    role: server
spec:
  restartPolicy: Never
  containers:
  - name: server-container
    image: thechargedneutron/kvs:server
    imagePullPolicy: Always
    securityContext:
      privileged: true
    env:
    - name: SERVER_ID
      value: SERVER_ID_DUMMY
  imagePullSecrets:
  - name: regcred
  nodeSelector:
    role: general
  hostNetwork: true
